[package]
name = "tree-edit-distance"
version = "0.1.0"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
edition = "2018"
description = "Find the lowest cost sequence of edits between two trees"
repository = "https://github.com/brunocodutra/tree-edit-distance.git"
license = "MIT"
readme = "README.md"
keywords = ["diff", "tree", "distance", "levenshtein", "lcs"]
categories = ["algorithms"]

[dependencies]
arrayvec = "0.5.1"
itertools = "0.9.0"
